server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://119.3.106.81:3306/christmas
    username: lemon
    password: zhang123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

